language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
before_install:
  - cd ..
  - git clone https://github.com/pfadipatria/hitobito.git
  - git clone https://github.com/pfadipatria/hitobito_patria.git
  - cd hitobito
install:
  - bundle install
  - rake db:create
  - rake db:setup:all
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec