language: ruby
rvm:
  - "1.9.3"
services: memcached
before_install:
  - cd ..
  - git clone https://github.com/pfadipatria/hitobito.git
  - git clone https://github.com/pfadipatria/hitobito_pbs.git
  - cd hitobito
  - cp Wagonfile.ci Wagonfile
install: bundle
before_script:
  - bundle exec rake environment RAILS_ENV=development db:create
  - bundle exec rake environment RAILS_ENV=development db:setup:all
  - bundle exec rake environment RAILS_ENV=development db:test:prepare
script:
  - bundle exec rspec