# This is where the button 'change password' leads to, if logged in as a ldap-user
ldap_edit_password: http://www.pfadipatria.com

# This is where you get redirected to, if you forgot your password and request a new one as an ldap-user
ldap_new_password: http://www.hitobito.ch